//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeff.Jones.JLogger8.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jeff.Jones.JLogger8.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] circlej {
            get {
                object obj = ResourceManager.GetObject("circlej", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to close the debug log file properly due to an unexpected error..
        /// </summary>
        internal static string CLOSE_LOGFILE_UNHANDLED_TITLE {
            get {
                return ResourceManager.GetString("CLOSE_LOGFILE_UNHANDLED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last line in the log.
        /// </summary>
        internal static string LAST_LINE_IN_LOG {
            get {
                return ResourceManager.GetString("LAST_LINE_IN_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Physical RAM=[{0}]..
        /// </summary>
        internal static string LOG_AVAIL_RAM {
            get {
                return ResourceManager.GetString("LOG_AVAIL_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLR Version=[{0}].
        /// </summary>
        internal static string LOG_CLR_VERSION {
            get {
                return ResourceManager.GetString("LOG_CLR_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line=[{0}]..
        /// </summary>
        internal static string LOG_COMMAND_LINE {
            get {
                return ResourceManager.GetString("LOG_COMMAND_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer domain name=[{0}]..
        /// </summary>
        internal static string LOG_COMPUTERDOMAINNAME {
            get {
                return ResourceManager.GetString("LOG_COMPUTERDOMAINNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer name=[{0}].
        /// </summary>
        internal static string LOG_COMPUTERNAME {
            get {
                return ResourceManager.GetString("LOG_COMPUTERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Time Zone=[{0}].
        /// </summary>
        internal static string LOG_CURR_TZ {
            get {
                return ResourceManager.GetString("LOG_CURR_TZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Time Zone (Daylight Savings Name)=[{0}].
        /// </summary>
        internal static string LOG_CURR_TZ_DS {
            get {
                return ResourceManager.GetString("LOG_CURR_TZ_DS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS Host Name=[{0}].
        /// </summary>
        internal static string LOG_DNS_HOST_NAME {
            get {
                return ResourceManager.GetString("LOG_DNS_HOST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daylight Savings Time=[{0}].
        /// </summary>
        internal static string LOG_DST {
            get {
                return ResourceManager.GetString("LOG_DST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full computer name=[{0}].
        /// </summary>
        internal static string LOG_FULLCOMPUTERNAME {
            get {
                return ResourceManager.GetString("LOG_FULLCOMPUTERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer is in a domain=[{0}]..
        /// </summary>
        internal static string LOG_IS_IN_DOMAIN {
            get {
                return ResourceManager.GetString("LOG_IS_IN_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer is in a domain=[{0}]..
        /// </summary>
        internal static string LOG_IS_IN_DOMAIN1 {
            get {
                return ResourceManager.GetString("LOG_IS_IN_DOMAIN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of processors=[{0}].
        /// </summary>
        internal static string LOG_NUM_PROCS {
            get {
                return ResourceManager.GetString("LOG_NUM_PROCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Platform=[{0}].
        /// </summary>
        internal static string LOG_OS_PLATFORM {
            get {
                return ResourceManager.GetString("LOG_OS_PLATFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Service Pack=[{0}].
        /// </summary>
        internal static string LOG_OS_SERVICE_PACK {
            get {
                return ResourceManager.GetString("LOG_OS_SERVICE_PACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Version=[{0}].
        /// </summary>
        internal static string LOG_OS_VERSION {
            get {
                return ResourceManager.GetString("LOG_OS_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running in the Visual Studio IDE=[{0}]..
        /// </summary>
        internal static string LOG_RUNNING_IN_IDE {
            get {
                return ResourceManager.GetString("LOG_RUNNING_IN_IDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Directory=[{0}].
        /// </summary>
        internal static string LOG_SYS_DIR {
            get {
                return ResourceManager.GetString("LOG_SYS_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interactive=[{0}].
        /// </summary>
        internal static string LOG_USR_INTERACTIVE {
            get {
                return ResourceManager.GetString("LOG_USR_INTERACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete file [{0}]. User permissions for the service user account may need to be checked for the file. Error Message: [{1}].
        /// </summary>
        internal static string PROCESSLOGRETENTION_FILEDELETE_MSG {
            get {
                return ResourceManager.GetString("PROCESSLOGRETENTION_FILEDELETE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete RMCMC log files older than [{0}] due to an unexpected error. Error Message: [{1}].
        /// </summary>
        internal static string PROCESSLOGRETENTION_UNHANDLED_MSG {
            get {
                return ResourceManager.GetString("PROCESSLOGRETENTION_UNHANDLED_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start log processing timer to an unexpected error..
        /// </summary>
        internal static string START_TIMER_ERROR {
            get {
                return ResourceManager.GetString("START_TIMER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the debug log file due to an unexpected error..
        /// </summary>
        internal static string UNABLE_TO_CREATE_DEBUG_LOG_TITLE {
            get {
                return ResourceManager.GetString("UNABLE_TO_CREATE_DEBUG_LOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the debug file for writing..
        /// </summary>
        internal static string UNABLE_TO_OPEN_DEBUG_LOG_TITLE {
            get {
                return ResourceManager.GetString("UNABLE_TO_OPEN_DEBUG_LOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process debug log items due to an unexpected error..
        /// </summary>
        internal static string UNABLE_TO_PROCESS_DEBUG_LOG_ITEM_TITLE {
            get {
                return ResourceManager.GetString("UNABLE_TO_PROCESS_DEBUG_LOG_ITEM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process log queue event to an unexpected error..
        /// </summary>
        internal static string UNABLE_TO_PROCESS_QUEUE {
            get {
                return ResourceManager.GetString("UNABLE_TO_PROCESS_QUEUE", resourceCulture);
            }
        }
    }
}
